// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG1Y816QoxtMUSpnJsCN8D4bWtvGIJumQ',
    appId: '1:955262892747:web:193f6da7624027ea0a394e',
    messagingSenderId: '955262892747',
    projectId: 'orchard-mobile-30d71',
    authDomain: 'orchard-mobile-30d71.firebaseapp.com',
    storageBucket: 'orchard-mobile-30d71.appspot.com',
    measurementId: 'G-24C52K8GNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPkxmelq8gwzwk7UA5thIgkxs6tLymXhk',
    appId: '1:955262892747:android:ea79cd6e235885840a394e',
    messagingSenderId: '955262892747',
    projectId: 'orchard-mobile-30d71',
    storageBucket: 'orchard-mobile-30d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAthGlFY94BdVTz4HSzcy2LOGT7b8mzSz0',
    appId: '1:955262892747:ios:8e7dc913bcd27f670a394e',
    messagingSenderId: '955262892747',
    projectId: 'orchard-mobile-30d71',
    storageBucket: 'orchard-mobile-30d71.appspot.com',
    iosClientId: '955262892747-oeptikpltdfprp83mp81okc5g283smnl.apps.googleusercontent.com',
    iosBundleId: 'com.orchard.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAthGlFY94BdVTz4HSzcy2LOGT7b8mzSz0',
    appId: '1:955262892747:ios:8e7dc913bcd27f670a394e',
    messagingSenderId: '955262892747',
    projectId: 'orchard-mobile-30d71',
    storageBucket: 'orchard-mobile-30d71.appspot.com',
    iosClientId: '955262892747-oeptikpltdfprp83mp81okc5g283smnl.apps.googleusercontent.com',
    iosBundleId: 'com.orchard.app',
  );
}
